# am-help.ps1 - Show all am commands
# Usage: am --upaupa

Write-Host ""
Write-Host "am Windows Commands"
Write-Host "==================="
Write-Host ""
Write-Host "=== setup (run once, in order) ==="
Write-Host "  am upa                 Install WSL + Podman (requires Admin)"
Write-Host "  am -pm                 Create ammachine (podman machine)"
Write-Host ""
Write-Host "=== daily use ==="
Write-Host "  am                     Start ammachine + SSH into it"
Write-Host "  am -n                  Dry run (show what would happen)"
Write-Host ""
Write-Host "=== maintenance ==="
Write-Host "  am -u                  Update WSL/Podman versions (requires Admin)"
Write-Host "  am -u -n               Dry run update"
Write-Host "  gn                     Stop ammachine"
Write-Host "  gn -pm                 Delete ammachine"
Write-Host "  gn upa                 Uninstall WSL + Podman (requires Admin)"
Write-Host ""
Write-Host "=== inside ammachine (after 'am') ==="
Write-Host "  upaupa                 Show all machine commands"
Write-Host ""
